backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.authtoken import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("users/", include("users.urls"), name='users'),
    #path("", auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path("",include("intranet.urls"), name="intranet"),
    path("cadastros/",include("cadastros.urls"), name='cadastros'),
    path("cms/", include("cms.urls"), name='cms'),
    #path("crm/", include("crm.urls"), name='crm'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/cadastros/urls.py
from django.urls import path, include
from .views import *
app_name = 'cadastros'
urlpatterns = [
    path('api/cidades/', CidadeList.as_view(), name='cidade_list_create'),
    path('api/bairros/',BairroList.as_view(), name='bairro_list_create'),
    path('api/logradouros/', LogradouroList.as_view(),name='logradouro_list_create'),
    path('api/pessoas/',PessoaFisicaList.as_view(),name='pessoa_fisica_list_create'),
    
    ################# URLS CRUD TEMPLATE #############
    path('cidades/',CidadesListView.as_view(), name='list_cidades'),

    ################ URLS CADASTRO DE BAIRROS ###############
    path('bairros/',BairroListView.as_view(), name='list_bairros'),
    path('bairros/create',BairroCreateView.as_view(), name='create_bairro'),
    path('bairros/edit/<int:pk>',BairroEditView.as_view(), name='edit_bairro'),
    path('bairros/remove/<int:pk>',BairroDeleteView.as_view(), name='remove_bairro'),
    
    ################ URLS CADASTRO DE LOGRADOURO ###############

    path('logradouros/',LogradourosListView.as_view(), name='list_logradouros'),
    path('logradouros/create',LogradouroCreateView.as_view(), name='create_logradouro'),
    path('ajax/get-bairros/', BuscaBairroCidade.as_view(), name='get_bairros'),

   
    path('pessoas/',PessoasListView.as_view(), name='list_pessoas'),
    path('pessoas/create/',PessoaFisicaCreateView.as_view(), name='create_pessoas'),
    path('pessoas/edit/<int:pk>',PessoaFisicaCreateView.as_view(), name='edit_pessoas'),
    path('pessoas/remove/<int:pk>',PessoaFisicaCreateView.as_view(), name='remove_pessoas'),
    path('pessoas/detail/<int:pk>',PessoaFisicaCreateView.as_view(), name='detail_pessoas'),

]

backend/cms/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


app_name = 'cms'

urlpatterns = [
    path('campanha/list', BannerListView.as_view(), name='banner_list'),
    path('campanha/create/', BannerCampanhaCreateView.as_view(), name='create_campanha'),
    path('campanha/edit/<int:pk>', BannerCampanhaEditView.as_view(), name='edit_campanha'),
    path('campanha/remove/<int:pk>', BannerCampanhaDeleteView.as_view(), name='remove_campanha'),
    path('campanha/detail/<int:pk>', BannerCampanhaDetailView.as_view(), name='detail_campanha'),
]

backend/cadastros/models.py
from django.db import models

# Create your models here.

STATE_CHOICES = ( 
	('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), 
	('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), 
	('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), 
	('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), 
	('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), 
	('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), 
	('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'),
	('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), 
	('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), 
	('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')
)


class Cidade(models.Model):
	nome = models.CharField(max_length=60)
	estado = models.CharField(max_length=2, choices=STATE_CHOICES)

	def __unicode__(self):
		return self.nome
	
	def __str__(self):
		return f'{self.nome} - {self.estado}'

class Bairro(models.Model):
	nome = models.CharField(max_length=60)
	cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
	def __str__(self):
			return f'{self.nome} - {self.cidade}'
	class Meta:
		unique_together = ['nome','cidade']
		ordering = ['cidade','nome']

	
	
class Logradouro(models.Model):
	nome = models.CharField(max_length=60)
	bairro = models.ForeignKey(Bairro,on_delete=models.CASCADE)
	cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)

	class Meta:
		unique_together = ['nome','bairro','cidade']
		ordering = ['cidade']

	def __str__(self):
		return '%d: %s' % (self.nome, self.cidade)
	
class PessoaFisica(models.Model):
	SEXO = (
		('M','MASCULINO'),('F','FEMININO')
		)
	nome = models.CharField(max_length=255)
	data_nascimento = models.DateField(null=True)
	cpf = models.CharField(max_length=11,null=True,blank=True)
	sexo = models.CharField(choices=SEXO)
	email = models.EmailField(blank=True,null=True)
	telefone = models.CharField(max_length=255,null=True,blank=True)

class EnderecoPessoaFisica(models.Model):
	TIPOENDERECO = (
		('R','RESIDENCIAL'),
		('C','COMERCIAL'),
		('O','OUTROS')
	)
	pessoa = models.ForeignKey(PessoaFisica, related_name='enderecos',on_delete=models.CASCADE)
	cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
	bairro = models.ForeignKey(Bairro, on_delete=models.CASCADE)
	logradouro = models.ForeignKey(Logradouro, on_delete=models.CASCADE)
	tipo_endereco = models.CharField(choices=TIPOENDERECO,max_length=1)
	numero = models.IntegerField(blank=True,null=True)
	cep = models.CharField(max_length=8)
	
	class Meta:
		unique_together = ['pessoa','bairro','logradouro','numero']
		ordering = ['-id']

class ContatoPessoaFisica(models.Model):
	TIPOCONTATO = (
		('T','TELEFONE'),
		('C','CELULAR'),
		('E','EMAIL'),
		('O','OUTROS')
	)
	pessoa = models.ForeignKey(PessoaFisica, related_name='contatos', on_delete=models.CASCADE)
	tipo_contato = models.CharField(choices=TIPOCONTATO,max_length=1)
	contato = models.CharField(max_length=60)
	principal = models.BooleanField(default=False)

	class Meta:
		unique_together = ['pessoa','principal']

backend/cadastros/views.py
from django.urls import reverse_lazy
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalReadView, BSModalUpdateView, BSModalDeleteView
from django.shortcuts import render
from rest_framework import generics
from .models import *
from .serializers import *
from .forms import *
# Create your views here.


class CidadeList(generics.ListCreateAPIView):
    queryset = Cidade.objects.all()
    serializer_class = CidadeSerializer

class CidadeCRUD(generics.RetrieveUpdateDestroyAPIView):
    queryset = Cidade.objects.all()
    serializer_class = CidadeSerializer

class BairroList(generics.ListCreateAPIView):
    queryset = Bairro.objects.all()
    serializer_class = BairroSerializer

class BairroCRUD(generics.RetrieveUpdateDestroyAPIView):
    queryset = Bairro.objects.all()
    serializer_class = BairroSerializer

class LogradouroList(generics.ListCreateAPIView):
    queryset = Logradouro.objects.all()
    serializer_class = LogradouroSerializer

class LogradouroCRUD(generics.RetrieveUpdateDestroyAPIView):
    queryset = Logradouro.objects.all()
    serializer_class = LogradouroSerializer

class PessoaFisicaList(generics.ListCreateAPIView):
    queryset = PessoaFisica.objects.all()
    serializer_class = PessoaFisicaSerializerCompleto

class PessoasCRUD(generics.RetrieveUpdateDestroyAPIView):
    queryset = PessoaFisica.objects.all()
    serializer_class = PessoaFisicaSerializer

class EnderecoPessoaFisicaList(generics.ListCreateAPIView):
    queryset = EnderecoPessoaFisica.objects.all()
    serializer_class = EnderecoPessoaFisicaSerializer




#######################################################
########### VIEWS DE ENDEREÇAMENTO ####################
#######################################################

from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

##### LIST CIDADES ######

class CidadesListView(View, LoginRequiredMixin):
    
    login_url = '/users/login/'
    
    def get(self,request):
        cidades = Cidade.objects.all().order_by('id').values()
        context = {
            'cidades' : cidades,
            'page_title' : 'Cadastro de Cidades'
        }
        return render(request,"cadastros/cidades/list_cidades.html", context=context)


##### LIST BAIRROS ######

class BairroListView(View, LoginRequiredMixin):
    login_url = '/users/login/'
    def get(self,request):
        bairros = Bairro.objects.all().order_by('cidade')
        context = {
            'bairros' : bairros,
            'page_title' : 'Cadastro de Bairros'
        }
        return render(request,"cadastros/bairros/list_bairros.html", context=context)

###### CRIA BAIRROS #######

class BairroCreateView(BSModalCreateView, LoginRequiredMixin):
    login_url = '/user/login/'
    template_name = 'generic/create.html'
    form_class = BairroModelForm
    success_message = 'Bairro criado com sucesso.'
    success_url = reverse_lazy('cadastros:list_bairros')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        context["modal_title"] = 'Criar bairro'
        context["hint"] = '*Ao criar um bairro verifique se o mesmo já não existe no sistema.'

        return context


###### EDITA BAIRROS  #######


class BairroEditView(BSModalUpdateView, LoginRequiredMixin):
    login_url = '/user/login/'
    model = Bairro
    template_name = 'generic/edit.html'
    form_class = BairroModelForm
    success_message = 'Bairro editado com sucesso!'
    success_url = reverse_lazy('cadastros:list_bairros')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        context["modal_title"] = 'Editar bairro'
        context["hint"] = '*Cuidado, você está editando um bairro do sistema.'

        return context


class BairroDeleteView(BSModalDeleteView, LoginRequiredMixin):
    login_url = '/user/login/'
    model = Bairro
    template_name = 'generic/delete.html'
    success_message = 'Bairro removido com sucesso.'
    error_message = 'Não foi possível remover este bairro.'
    success_url = reverse_lazy('cadastros:list_bairros')
    error_url = reverse_lazy('cadastros:list_bairros')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        context["modal_title"] = 'Remover bairro'
        context["hint"] = '*Cuidado, você está editando um bairro do sistema.'
        context["registro"] = self.object
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.error(request, "Não foi possível excluir o registro.")
        finally:
            return HttpResponseRedirect(success_url)



###################### VIEWS DO CADASTRO DE LOGRADOUROS ##########################
        
class LogradourosListView(View, LoginRequiredMixin):
    login_url = '/users/login/'
    def get(self,request):
        logradouros = Logradouro.objects.all().order_by('cidade')
        context = {
            'logradouros' : logradouros,
            'page_title' : 'Cadastro de Logradouros'
        }
        return render(request,"cadastros/logradouros/list_logradouros.html", context=context)


class LogradouroCreateView(BSModalCreateView, LoginRequiredMixin):
    login_url = '/user/login/'
    template_name = 'generic/create.html'
    form_class = LogradouroModelForm
    success_message = 'Logradouro criado com sucesso.'
    success_url = reverse_lazy('cadastros:list_logradouros')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        context["modal_title"] = 'Criar logradouro'
        context["hint"] = '*Ao criar um logradouro verifique se o mesmo já não existe no sistema.'

        return context


from django.http import JsonResponse


class BuscaBairroCidade(LoginRequiredMixin,View):
    login_url = '/user/login/'
    
    def get(self, request):
        cidade = request.GET.get('cidade')
        bairros = Bairro.objects.filter(cidade=cidade).order_by('nome')
        return JsonResponse(list(bairros.values('id','nome')),safe=False)
        




from django.urls import reverse_lazy
from .forms import PessoaFisicaModalForm
from .models import PessoaFisica
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalReadView, BSModalUpdateView, BSModalDeleteView
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView



class PessoasListView(View, LoginRequiredMixin):
    login_url = '/users/login/'
    def get(self,request):
        pessoas = PessoaFisica.objects.all().order_by('id').values()
        context = {
            'pessoas' : pessoas,
            'page_title' : 'Cadastro de Pessoas'
        }
        return render(request,"cadastros/pessoas/list_pessoas.html", context=context)



class PessoaFisicaInLine():
    form_class = PessoaFisicaModalForm
    model = PessoaFisica
    template_name = "cadastros/pessoa/create.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        self.object = form.save()

        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('cadastros:list_pessoas')

    def formset_endereco_valid(self, formset):

        enderecos = formset.save(commit=False)  
        # self.save_formset(formset, contact)
        # add this 2 lines, if you have can_delete=True parameter 
        # set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for endereco in enderecos:
            endereco.pessoa = self.object
            endereco.save()

    def formset_contato_valid(self, formset):
        
        contatos = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this 2 lines, if you have can_delete=True parameter 
        # set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for contato in contatos:
            contato.pessoa = self.object
            contato.save()

class PessoaFisicaCreateView(PessoaFisicaInLine, BSModalCreateView,LoginRequiredMixin):
    login_url = '/user/login/'
    template_name = 'cadastros/pessoas/create.html'
    form_class = PessoaFisicaModalForm
    success_message = 'Pessoa cadastrada com sucesso.'
    success_url = reverse_lazy('cadastros:list_pessoas')
    
    def get_context_data(self, **kwargs):
        ctx = super(PessoaFisicaCreateView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'enderecos': EnderecoFormSet(prefix='enderecos'),
                'contatos': ContatoFormSet(prefix='contatos'),
            }
        else:
            return {
                'enderecos': EnderecoFormSet(self.request.POST or None, self.request.FILES or None, prefix='enderecos'),
                'contatos': ContatoFormSet(self.request.POST or None, self.request.FILES or None, prefix='contatos'),
            }

backend/templates/cadastros/pessoas/list_pessoas.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <button id="create_pessoas" class="mt-3 mb-3 btn btn-primary" type="button" name="button">+ Pessoa</button>
<section>
    <table id="pessoasTable" class="table responsive display">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Data Nascimento</th>
                <th>CPF</th>
                <th>Sexo</th>
                <th>E-mail</th>
                <th>Telefone</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for pessoa in pessoas %}
            <tr>
                <td>{{ pessoa.nome }}</td>
                <td>{{ pessoa.data_nascimento }}</td>
                <td>{{ pessoa.cpf }}</td>
                <td>{{ pessoa.sexo }}</td>
                <td>{{ pessoa.email }}</td>
                <td>{{ pessoa.telefone }}</td>
                <td>
                        {% if perms.cms.view_pessoafisica %}
                        <button type="button" class="view bs-modal btn btn-sm btn-primary" data-form-url="{% url 'cadastros:detail_pessoas' pessoa.id %}">
                            <span class="fa fa-eye"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.cms.edit_pessoafisica %}
                            <button type="button" class="edit bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'cadastros:edit_pessoas' pessoa.id %}">
                            <span class="fa fa-pen"></span>
                        </button>
                         {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.cms.delete_pessoafisica %}
                        <button type="button" class="delete bs-modal btn btn-sm btn-danger" data-form-url="{% url 'cadastros:remove_pessoas' pessoa.id %}">
                            <span class="fa fa-trash"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        </td>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog modal-xl	" role="document">
      <div class="modal-content"></div>
    </div>
</div>
{% include 'login/logout_modal.html' %}
{% endblock %}

{% block footer_scripts %}
<script>
    $(document).ready( function () {
    $('#pessoasTable').DataTable({
        language : {
            url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/pt-BR.json',
      }
    });
    });
    document.addEventListener('DOMContentLoaded', (e) => {
    modalForm(document.getElementById('create_pessoas'), {
    formURL: "{% url 'cadastros:create_pessoas' %}"
  })
});
document.addEventListener('DOMContentLoaded', (e) => {
  var deleteButtons = document.getElementsByClassName("delete");
  var editButtons = document.getElementsByClassName("edit");
  var viewButtons = document.getElementsByClassName("view");
  for (var index=0; index < deleteButtons.length; index++) {
    modalForm(deleteButtons[index], {
      formURL: deleteButtons[index]["dataset"]["formUrl"],
      isDeleteForm: true
    });
  };
  for (var index=0; index < editButtons.length; index++) {
    modalForm(editButtons[index], {
      formURL: editButtons[index]["dataset"]["formUrl"],
    });
  };
  for (var index=0; index < viewButtons.length; index++) {
    modalForm(viewButtons[index], {
      formURL: viewButtons[index]["dataset"]["formUrl"],
    });
  }
});


</script>
{% endblock footer_scripts %}