backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.authtoken import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("users/", include("users.urls"), name='users'),
    #path("", auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path("",include("intranet.urls"), name="intranet"),
    path("cadastros/",include("cadastros.urls"), name='cadastros'),
    path("cms/", include("cms.urls"), name='cms'),
    #path("crm/", include("crm.urls"), name='crm'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/cms/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


app_name = 'cms'

urlpatterns = [
    path('campanha/list', BannerListView.as_view(), name='banner_list'),
    path('campanha/create/', BannerCampanhaCreateView.as_view(), name='create_campanha'),
    path('campanha/edit/<int:pk>', BannerCampanhaEditView.as_view(), name='edit_campanha'),
    path('campanha/remove/<int:pk>', BannerCampanhaDeleteView.as_view(), name='remove_campanha'),
    path('campanha/detail/<int:pk>', BannerCampanhaDetailView.as_view(), name='detail_campanha'),
]

backend/intranet/urls.py
from django.urls import path, include
from .views import *
app_name = 'intranet'
urlpatterns = [
    path('api/unidades/', UnidadeListCreateAPIView.as_view(), name='unidade-list-create'),
    path('api/unidades/<int:pk>/', UnidadeDetailAPIView.as_view(), name='unidade-detail'),
    path('api/departamentos/', DepartamentoListCreateAPIView.as_view(), name='departamento-list-create'),
    path('api/departamentos/<int:pk>/', DepartamentoDetailAPIView.as_view(), name='departamento-detail'),
    path('api/cargos/', CargoListCreateAPIView.as_view(), name='cargo-list-create'),
    path('api/cargos/<int:pk>/', CargoDetailAPIView.as_view(), name='cargo-detail'),
    path('api/perfilcolaboradores/', PerfilColaboradorListCreateAPIView.as_view(), name='perfilcolaborador-list-create'),
    path('api/perfilcolaboradores/<int:pk>/', PerfilColaboradorDetailAPIView.as_view(), name='perfilcolaborador-detail'),
    path('api/comunicados/', ComunicadosListCreateAPIView.as_view(), name='comunicados-list-create'),
    path('api/comunicados/<int:pk>/', ComunicadosDetailAPIView.as_view(), name='comunicados-detail'),
    path('api/envioscomunicados/', EnviosComunicadosListCreateAPIView.as_view(), name='envioscomunicados-list-create'),
    path('api/envioscomunicados/<int:pk>/', EnviosComunicadosDetailAPIView.as_view(), name='envioscomunicados-detail'),
    path('api/meuscomunicados/', MeusComunicadosListCreateAPIView.as_view(), name='meuscomunicados-list-create'),
    path('api/meuscomunicados/<int:pk>/', MeusComunicadosDetailAPIView.as_view(), name='meuscomunicados-detail'),
    path('',EnterpriseHome.as_view(), name='enterprise_home'),

    ##### VIEWS DE CONFIGURAÇÃO ####
    ##### ECJ 22/11/2023 ###########
    ##### ##########################
    
    path('unidades/',UnidadesList.as_view(), name='create_unidade'),
    path('departamentos/',DepartamentosList.as_view(), name='create_departamento'),
    path('cargos/', CargosList.as_view(), name='create_cargo'),
    path('equipe/',EquipeListView.as_view(), name='equipe'),
    path('edit_perfil/<int:pk>',PerfilEdit.as_view(),name='perfil_edit'),
    path('create_perfil/<str:hashid>',PerfilCreateModalView.as_view(),name='perfil_create')

    
]

backend/cms/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class BannerCampanha(models.Model):
    titulo_campanha = models.CharField(max_length=255,verbose_name='Título')
    slogan_campanha = models.CharField(max_length=255,verbose_name='Texto')
    imagem_campanha = models.ImageField(upload_to='campanhas/')
    data_inicial = models.DateField()
    data_final = models.DateField()
    ativo = models.BooleanField()
    exibir_texto = models.BooleanField(default=False)


class CategoriaArtigo(models.Model):
    categoria = models.CharField(max_length=255)

class Artigo(models.Model):
    categoria = models.ForeignKey(CategoriaArtigo,on_delete=models.CASCADE)
    created_by = models.ForeignKey('users.User',on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255)
    texto = RichTextField()
    publicado = models.BooleanField(default=False)
    data_publicacao = models.DateField(auto_created=True,auto_now=True)

backend/templates/unidades/list_unidades.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <button id="create_unidade" class="mt-3 mb-3 btn btn-primary" type="button" name="button">+ Unidade</button>
<section>
    <table id="unidadeTable" class="table responsive display">
        <thead>
            <tr>
                <th>Nome</th>
                <th>CNPJ</th>
                <th>Ativo</th>
                <th>Ações</th>

            </tr>
        </thead>
        <tbody>
            {% for unidade in unidades %}
            <tr>
                <td>{{ unidade.nome }}</td>
                <td>{{ unidade.cnpj}}</td>
                <td>{{ unidade.ativo }}</td>
                <td>
                        {% if perms.cms.view_bannercampanha %}
                        <button type="button" class="view bs-modal btn btn-sm btn-primary" data-form-url="#">
                            <span class="fa fa-eye"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.cms.edit_bannercampanha %}
                            <button type="button" class="edit bs-modal btn btn-sm btn-secondary" data-form-url="#">
                            <span class="fa fa-pen"></span>
                        </button>
                         {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.cms.delete_bannercampanha %}
                        <button type="button" class="delete bs-modal btn btn-sm btn-danger" data-form-url="#">
                            <span class="fa fa-trash"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        </td>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
{% include 'login/logout_modal.html' %}
{% endblock %}

{% block footer_scripts %}
<script>
    $(document).ready( function () {
    $('#unidadeTable').DataTable();
    });
    document.addEventListener('DOMContentLoaded', (e) => {
    modalForm(document.getElementById('create_unidade'), {
    formURL: "{% url 'intranet:create_unidade' %}"
  })
});
</script>
{% endblock footer_scripts %}