backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.authtoken import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("users/", include("users.urls"), name='users'),
    #path("", auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path("",include("intranet.urls"), name="intranet"),
    path("cadastros/",include("cadastros.urls"), name='cadastros'),
    path("cms/", include("cms.urls"), name='cms'),
    #path("crm/", include("crm.urls"), name='crm'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/cadastros/urls.py
from django.urls import path, include
from .views import *
app_name = 'cadastros'
urlpatterns = [
    path('api/cidades/', CidadeList.as_view(), name='cidade_list_create'),
    path('api/bairros/',BairroList.as_view(), name='bairro_list_create'),
    path('api/logradouros/', LogradouroList.as_view(),name='logradouro_list_create'),
    path('api/pessoas/',PessoaFisicaList.as_view(),name='pessoa_fisica_list_create'),
    
    ################# URLS CRUD TEMPLATE #############
    path('cidades/',CidadesListView.as_view(), name='list_cidades'),

    ################ URLS CADASTRO DE BAIRROS ###############
    path('bairros/',BairroListView.as_view(), name='list_bairros'),
    path('bairros/create',BairroCreateView.as_view(), name='create_bairro'),
    path('bairros/edit/<int:pk>',BairroEditView.as_view(), name='edit_bairro'),
    path('bairros/remove/<int:pk>',BairroDeleteView.as_view(), name='remove_bairro'),
    
    ################ URLS CADASTRO DE LOGRADOURO ###############

    path('logradouros/',LogradourosListView.as_view(), name='list_logradouros'),
    path('logradouros/create',LogradouroCreateView.as_view(), name='create_logradouro'),
    path('ajax/get-bairros/', BuscaBairroCidade.as_view(), name='get_bairros'),

   
    path('pessoas/',PessoasListView.as_view(), name='list_pessoas'),
    path('pessoas/create/',PessoaFisicaCreateView.as_view(), name='create_pessoas'),
    path('pessoas/edit/<int:pk>',PessoaFisicaCreateView.as_view(), name='edit_pessoas'),
    path('pessoas/remove/<int:pk>',PessoaFisicaCreateView.as_view(), name='remove_pessoas'),
    path('pessoas/detail/<int:pk>',PessoaFisicaCreateView.as_view(), name='detail_pessoas'),

]

backend/cms/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


app_name = 'cms'

urlpatterns = [
    path('campanha/list', BannerListView.as_view(), name='banner_list'),
    path('campanha/create/', BannerCampanhaCreateView.as_view(), name='create_campanha'),
    path('campanha/edit/<int:pk>', BannerCampanhaEditView.as_view(), name='edit_campanha'),
    path('campanha/remove/<int:pk>', BannerCampanhaDeleteView.as_view(), name='remove_campanha'),
    path('campanha/detail/<int:pk>', BannerCampanhaDetailView.as_view(), name='detail_campanha'),
]

backend/users/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import logout_then_login


app_name = 'users'

urlpatterns = [
    path("login_rest/", obtain_auth_token, name='login'),
    path("list/", user_list, name='user_list'),
    path("create/", user_create, name='user_create'),
    path("manage/<int:pk>/",user_crud,name="user_crud"),
    path("perms/",manage_perms, name='manage_perms'),
    path('login/', classic_login, name='login'),
    path('logout/', logout_then_login, name='logout'),
    path('permissoes/<int:user_id>/', manage_perms_classic, name='manage_user_perms'),
    path('create_user/',UserCreateModalView.as_view(),name='create_user'),
    path('detail/<int:pk>',UserDetailView.as_view(),name='detail_user'),
    path("edit/<int:pk>/", UserEditView.as_view(), name='user_edit'),
    path('password_reset/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('password_reset/<uidb64>/<token>/', PasswordResetView.as_view(), name='password_reset'),
]

backend/cms/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class BannerCampanha(models.Model):
    titulo_campanha = models.CharField(max_length=255,verbose_name='Título')
    slogan_campanha = models.CharField(max_length=255,verbose_name='Texto')
    imagem_campanha = models.ImageField(upload_to='campanhas/')
    data_inicial = models.DateField()
    data_final = models.DateField()
    ativo = models.BooleanField()
    exibir_texto = models.BooleanField(default=False)


class CategoriaArtigo(models.Model):
    categoria = models.CharField(max_length=255)

class Artigo(models.Model):
    categoria = models.ForeignKey(CategoriaArtigo,on_delete=models.CASCADE)
    created_by = models.ForeignKey('users.User',on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255)
    texto = RichTextField()
    publicado = models.BooleanField(default=False)
    data_publicacao = models.DateField(auto_created=True,auto_now=True)

backend/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    first_name = models.CharField(max_length=255,verbose_name="Nome",null=True)
    last_name = models.CharField(max_length=255,verbose_name="Sobrenome",null=True)
    username = None
    email = models.EmailField(unique=True, verbose_name="E-mail")
    cpf = models.CharField(max_length=11,verbose_name="CPF")
    telefone = models.CharField(max_length=11,verbose_name="Telefone")
    data_nascimento = models.DateField(blank=True, null=True,verbose_name="Data de Nascimento")
    password_set = models.BooleanField(default=False,)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["cpf","data_nascimento","username"]
    EMAIL_FIELD = 'email'

    def to_dict_verbose(self,fields):
        data = {}
        for field in self._meta.fields:
                if field.name in fields:
                    verbose_name = field.verbose_name
                    value = getattr(self, field.attname)
                    data[verbose_name] = value
        return data

backend/templates/generic/campanha.html
<div class="container mt-2">
  
<!-- Carousel wrapper -->
<div id="carouselMaterialStyle" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <!-- Indicators -->
    {% for imagem in imagens_campanha %}

    <!-- Inner -->
    <div class="carousel-inner rounded-5 shadow-4-strong">
      <!-- Single item -->
      <div class="carousel-item {% if forloop.first %} active{% endif %}">
        <img src="{{imagem.imagem_campanha.url}}" class="d-block w-100"
          alt="{{imagem.titulo_campanha}}" />
        <div class="carousel-caption d-none d-md-block">
          {% if imagem.exibir_texto %}
          <h5>{{imagem.titulo_campanha}}</h5>
          <p>{{imagem.slogan_campanha}}</p>
          {% endif %}
        </div>
      </div>
    <!-- Inner -->

    <!-- Controls -->
    <button class="carousel-control-prev" type="button" data-mdb-target="#carouselMaterialStyle" data-mdb-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Anterior</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carouselMaterialStyle" data-mdb-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Próximo</span>
    </button>
    {% endfor %}

  </div>
  <!-- Carousel wrapper -->

  
</div>

backend/templates/generic/create.html
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">{{ modal_title|upper }}</h5>
    <button type="button" class="btn close btn-rounded btn-secondary" data-bs-dismiss="modal" data-dismiss="create-modal" aria-label="Fechar">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      <p>{{hint}}
      <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
  
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{field}}
          <div class="{% if field.errors %} invalid{% endif %}">
            {% for error in field.errors %}
              <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
  </div>


  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal" data-bs-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>

</form>

{% block script %}

<script>
  $(document).ready(function(){
    $('#id_cidade').change(function(){
        var url = "{% url 'cadastros:get_bairros' %}";
        var cidadeId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'id_cidade': cidadeId
            },
            success: function (data) {
                $("#id_bairro").html('<option value="">Escolha um bairro...</option>');
                data.forEach(function (bairro) {
                    $("#id_bairro").append('<option value="' + bairro.id + '">' + bairro.nome + '</option>');
                });
            }
        });
    });
});
</script>

{% endblock %}

backend/templates/generic/delete.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}


  <div class="modal-header">
    <h3 class="modal-title">{{modal_title|upper}}</h3>
    <button type="button" class="close btn btn-rounded btn-secondary" data-bs-dismiss="modal" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p>Você tem certeza que deseja remover o registro 
      <strong>{{ registro|upper }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>

</form>

backend/templates/generic/detail.html
{% load widget_tweaks %}

<div class="modal-header">
  <h5 class="modal-title">{{ modal_title }}</h5>
  <button type="button" class="btn close btn-rounded btn-secondary" data-bs-dismiss="modal" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <table class="table table-borderless">
    {% for key, value in dict_data.items %}
    <tr>
      <td>
        <strong>{{ key }}</strong>
      </td>
      <td>
        {{ value }}
      </td>
    </tr>
    {% endfor %}
</table>

</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default btn-primary bg-gradient" data-bs-dismiss="modal" data-dismiss="modal-view">Fechar</button>
</div>

backend/templates/generic/edit.html
{% load widget_tweaks %}

<form method="post" enctype="multipart/form-data" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{{modal_title}}</h3>
    <button type="button" class="close btn btn-rounded btn-secondary" data-bs-dismiss="modal" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{field}}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>

</form>

backend/templates/generic/list.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<div class="container">
    <button id="create_user" class="mt-3 mb-3 btn btn-primary" type="button" name="button">+ Usuário</button>
<section>
    <table id="equipeTable" class="table responsive display">
        <thead>
            <tr>
                <th>Imagem</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Unidade</th>
                <th>Departamento</th>
                <th>Função</th>
                <th>Aniversário</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            
            <tr>
                <td> 
                  {% if user.perfilcolaborador.imagem %}
                  <img src="/media/{{user.perfilcolaborador.imagem}}" class="avatar" style="max-height: 50px;max-width: 50px;">
                  {% else %}
                  <img src="{% static 'avatar-placeholder.gif' %}" class="avatar" style="max-height: 50px;max-width: 50px;">
                  {% endif %}
                </td>
                <td>{{ user.first_name }} {{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.perfilcolaborador.unidade }}</td>
                <td>{{ user.perfilcolaborador.departamento }}</td>
                <td>{{ user.perfilcolaborador.cargo }}</td>
                <td>{{ user.data_nascimento }}</td>
                
        
                <td>
                        {% if perms.users.view_user %}
                        <button type="button" class="view bs-modal btn btn-sm btn-primary" data-form-url="{% url 'users:detail_user' user.id %}">
                            <span class="fa fa-eye"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.users.edit_user %}
                            <button type="button" class="edit bs-modal btn btn-sm btn-secondary" data-form-url="#">
                            <span class="fa fa-pen"></span>
                        </button>
                         {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.users.delete_user %}
                        <button type="button" class="delete bs-modal btn btn-sm btn-danger" data-form-url="#">
                            <span class="fa fa-trash"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        </td>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
{% include 'login/logout_modal.html' %}
{% endblock %}

{% block footer_scripts %}
<script>
    $(document).ready( function () {
    $('#equipeTable').DataTable({
      language : {
            url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/pt-BR.json',
        }
      });
    });
    document.addEventListener('DOMContentLoaded', (e) => {
    modalForm(document.getElementById('create_user'), {
    formURL: "{% url 'users:create_user' %}"
  })
});
document.addEventListener('DOMContentLoaded', (e) => {
  var deleteButtons = document.getElementsByClassName("delete");
  var editButtons = document.getElementsByClassName("edit");
  var viewButtons = document.getElementsByClassName("view");
  for (var index=0; index < deleteButtons.length; index++) {
    modalForm(deleteButtons[index], {
      formURL: deleteButtons[index]["dataset"]["formUrl"],
      isDeleteForm: true
    });
  };
  for (var index=0; index < editButtons.length; index++) {
    modalForm(editButtons[index], {
      formURL: editButtons[index]["dataset"]["formUrl"],
    });
  };
  for (var index=0; index < viewButtons.length; index++) {
    modalForm(viewButtons[index], {
      formURL: viewButtons[index]["dataset"]["formUrl"],
    });
  }
});

</script>
{% endblock footer_scripts %}

backend/templates/generic/list_campanha.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <button id="create_campanha" class="mt-3 mb-3 btn btn-primary" type="button" name="button">+ Campanha</button>
<section>
    <table id="campanhaTable" class="table responsive display">
        <thead>
            <tr>
                <th>Título</th>
                <th>Data Inicial</th>
                <th>Data Final</th>
                <th>Imagem</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for campanha in campanhas %}
            <tr>
                <td>{{ campanha.titulo_campanha }}</td>
                <td>{{ campanha.data_inicial}}</td>
                <td>{{ campanha.data_final }}</td>
                <td><img  src='/media/{{campanha.imagem_campanha}}' class="img-thumbnail" /></td>
                <td>{% if campanha.ativo %}Sim{%else%}Não{%endif%}</td>
                <td>
                        {% if perms.cms.view_bannercampanha %}
                        <button type="button" class="view bs-modal btn btn-sm btn-primary" data-form-url="{% url 'cms:detail_campanha' campanha.id %}">
                            <span class="fa fa-eye"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.cms.edit_bannercampanha %}
                            <button type="button" class="edit bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'cms:edit_campanha' campanha.id %}">
                            <span class="fa fa-pen"></span>
                        </button>
                         {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        {% if perms.cms.delete_bannercampanha %}
                        <button type="button" class="delete bs-modal btn btn-sm btn-danger" data-form-url="{% url 'cms:remove_campanha' campanha.id %}">
                            <span class="fa fa-trash"></span>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-sm btn-secondary">
                            <span class="fa fa-lock"></span>
                        </button>
                        {% endif %}
                        </td>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
</div>
{% include 'login/logout_modal.html' %}
{% endblock %}

{% block footer_scripts %}
<script>
    $(document).ready( function () {
    $('#campanhaTable').DataTable({
      language : {
            url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/pt-BR.json',
        }
      });
    });
    document.addEventListener('DOMContentLoaded', (e) => {
    modalForm(document.getElementById('create_campanha'), {
    formURL: "{% url 'cms:create_campanha' %}"
  })
});
document.addEventListener('DOMContentLoaded', (e) => {
  var deleteButtons = document.getElementsByClassName("delete");
  var editButtons = document.getElementsByClassName("edit");
  var viewButtons = document.getElementsByClassName("view");
  for (var index=0; index < deleteButtons.length; index++) {
    modalForm(deleteButtons[index], {
      formURL: deleteButtons[index]["dataset"]["formUrl"],
      isDeleteForm: true
    });
  };
  for (var index=0; index < editButtons.length; index++) {
    modalForm(editButtons[index], {
      formURL: editButtons[index]["dataset"]["formUrl"],
    });
  };
  for (var index=0; index < viewButtons.length; index++) {
    modalForm(viewButtons[index], {
      formURL: viewButtons[index]["dataset"]["formUrl"],
    });
  }
});


</script>
{% endblock footer_scripts %}